language: java

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn verify && bash <(curl -s https://codecov.io/bash)

deploy:
  -
    provider: script
    script: mvn --settings=./.travis/settings.xml jar:jar deploy:deploy
    on:
      branch: develop